import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <header>
                        <SignedOut>
                            <SignInButton />
                        </SignedOut>
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                        <nav style={{ display: 'flex', alignItems: 'center', border: '1px solid #ccc', padding: '10px', borderRadius: '5px' }}>
                            <Link href="/feed" style={{ marginRight: '15px', border: '1px solid #000', padding: '5px', borderRadius: '3px' }} className="link-hover">Feed</Link>
                            <Link href="/makeArt" style={{ border: '1px solid #000', padding: '5px', borderRadius: '3px' }} className="link-hover">Make Art</Link>
                            <Link href="/test-page" style={{ border: '1px solid #000', padding: '5px', borderRadius: '3px' }} className="link-hover">Test Page</Link>
                        </nav>
                    </header>
                    <main>{children}</main>
                </body>
            </html>
        </ClerkProvider>
    );
}
